openapi: 3.0.3
info:
  title: Easyappz Ads API
  version: 1.1.0
  description: |
    In-memory Ads domain. Only HTTP, no DB. JWT via Authorization header if needed.
servers:
  - url: /
paths:
  /api/ads:
    get:
      summary: List ads
      description: |
        Return list of ads with pagination. Sorting by popularity (view_count desc) or by published date (nulls last).
      parameters:
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [popular, date]
            default: popular
          description: Sort by popularity or date
        - name: category
          in: query
          required: false
          schema:
            type: string
          description: |
            Filter by category (exact match, case-insensitive). Empty or "Все" means no filter.
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of ads
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdsListResponse'
              examples:
                sample:
                  value:
                    count: 1
                    limit: 20
                    offset: 0
                    results:
                      - id: "f0c7d7a9-0e9d-4a3c-8f34-2a23d1b3b9b0"
                        source_url: "https://www.avito.ru/some_ad"
                        title: "iPhone 12 128GB"
                        image_url: "https://example.com/image.jpg"
                        published_at: "2023-11-15T10:00:00Z"
                        category: "Смартфоны"
                        view_count: 12
                        created_at: "2025-01-01T12:00:00Z"
                        updated_at: "2025-01-01T12:00:00Z"
  /api/ads/resolve:
    post:
      summary: Resolve ad by Avito URL
      description: |
        If ad with given source URL exists, return it (200). Otherwise fetch minimal data from Avito, create in-memory ad and return it (201).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResolveRequest'
            examples:
              sample:
                value:
                  url: "https://www.avito.ru/moskva/telefony/iphone_12_128gb_123456789"
      responses:
        '200':
          description: Existing ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
        '201':
          description: Created ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/ads/{id}:
    get:
      summary: Get ad by id (increments views)
      description: Returns ad by id and increments its view_count
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/ads/{id}/comments:
    get:
      summary: List comments for ad
      description: |
        Returns comments for the given ad id, sorted by created_at ascending. Data is stored in process memory and is reset on server restart (this is expected and matches the requirements).
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comments list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Ad not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create comment for ad
      description: |
        Create a comment for the ad. Requires JWT in Authorization header (Bearer <token>). Data is kept in memory and resets on restart.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
      responses:
        '201':
          description: Created comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Ad not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/register/:
    post:
      summary: Register a new user
      description: Registers a user in-memory and returns JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: Registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/login/:
    post:
      summary: Login user
      description: Validates credentials and returns JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/me/:
    get:
      summary: Current user
      description: Returns the username of the authenticated user.
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Ad:
      type: object
      required: [id, source_url, category, view_count, created_at, updated_at]
      properties:
        id:
          type: string
          format: uuid
        source_url:
          type: string
          format: uri
        title:
          type: string
          nullable: true
        image_url:
          type: string
          nullable: true
        published_at:
          type: string
          format: date-time
          nullable: true
        category:
          type: string
        view_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    AdsListResponse:
      type: object
      properties:
        count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/Ad'
    ResolveRequest:
      type: object
      required: [url]
      properties:
        url:
          type: string
          format: uri
    Comment:
      type: object
      required: [id, ad_id, username, text, created_at]
      properties:
        id:
          type: string
          format: uuid
        ad_id:
          type: string
        username:
          type: string
        text:
          type: string
          minLength: 1
          maxLength: 2000
        created_at:
          type: string
          format: date-time
    CreateComment:
      type: object
      required: [text]
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 2000
    Error:
      type: object
      properties:
        detail:
          type: string
    AuthRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      required: [username, token]
      properties:
        username:
          type: string
        token:
          type: string
    Me:
      type: object
      required: [username]
      properties:
        username:
          type: string
